### ISSUE TITLE
[Fixed] Broken in 2017.1

### ISSUE THREAD

**Issue by Kolyasisan** [TheMasonX/UnityPCSS#2]
There's simply little to no effect. No PCSS is being applied. Definitely worked in 5.6.

**Comment by erherhh4herh** [comment]
yeah same. im using 2017.1.0b8

**Comment by 0Xero7** [comment]
Same here. On 2017.1.0f1

**Comment by bamfbamf** [comment]
Same here. Build 2017.1.0f3.

**Comment by looki666** [comment]
Same problem . Any updates ?

**Comment by TheMasonX** [comment]
The subshaders at the bottom were the issue. Unity changed the tags it looks for from "PCF_5x5" to "PCF_SOFT", so it was defaulting to the hard shadows. I added copies of the two subshaders (regular and the backup that doesn't rely on vertex shader info) with the changed names so that it'll work with both 5.5 and 5.6, and 2017.

I wanted to use the UNITY_VERSION postprocessing macro check to change just the names, rather than copying the subshaders, but it doesn't seem to work with altering tags like it does other things. Oh well, I'll have to drop support for them sometime, but most changes to the shader should work for both.

Also, sorry for the long delay, I started a new job, and haven't really spent any time programming or doing game development.
